### ISSUE TITLE
Cannot serve static files using Nginx in front of Logto

### ISSUE THREAD

**Issue by sunjianan9900** [logto-io/logto#1568]
Launched via:
```
curl -fsSL https://raw.githubusercontent.com/logto-io/logto/HEAD/docker-compose.yml | TAG=prerelease docker-compose -p logto -f - up -d
```

Can access via IP, but it shows no HTTPS:

![image](https://user-images.githubusercontent.com/10936316/179362089-5ec59fa7-e65f-4d01-ab4c-b7adcf8098ed.png)

Then I set domain and HTTPS via Nginx, which enables service access, but no static files.
And the project mount path remains unknown.

```
 upstream silly_face_society_upstream {
   server 127.0.0.1:3001;
   keepalive 64;
  }
```

Nginx config

```
  location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

       proxy_pass     http://silly_face_society_upstream;
       proxy_redirect off;
    }
```

Request
```
URL: https://xxxxxxxx/console/index.83bf1925.css
Method: GET
Status: 404 
```

Cannot access static files, do you have Nginx config template?

Hope docs can be more detailed.

<details>
<summary>Original Post</summary>

启动方法：
```
curl -fsSL https://raw.githubusercontent.com/logto-io/logto/HEAD/docker-compose.yml | TAG=prerelease docker-compose -p logto -f - up -d
```

可以正常通过ip访问，但是ip访问提示无HTTPS
![image](https://user-images.githubusercontent.com/10936316/179362089-5ec59fa7-e65f-4d01-ab4c-b7adcf8098ed.png)

然后通过Nginx设置域名和Https后，可以访问到服务，但是静态文件访问不到
但是项目目录也不知道挂载到哪里了

```
 upstream silly_face_society_upstream {
   server 127.0.0.1:3001;
   keepalive 64;
  }
```

```
  location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

       proxy_pass     http://silly_face_society_upstream;
       proxy_redirect off;
    }
```

访问时：
```
请求 URL: https://xxxxxxxx/console/index.83bf1925.css
请求方法: GET
状态代码: 404 
```

无法访问到静态文件，请问有没有Nginx 设置的模版呢？

希望文档可以再详细一下！
项目非常赞

</details>

**Comment by gao-sun** [comment]
hi @sunjianan9900,

Thank you for your feed back and detailed context.

Usually for URLs with HTTP protocol, the browser only provides a HTTPS context in `http://localhost`. Any other URLs start with `http://` will be not valid, including IP adresses.

If you put a Nginx in front of Logto, please make sure you set env `` to `true`. See [Using a HTTPS proxy](https://docs.logto.io/zh-cn/docs/references/core/configuration/#%E4%BD%BF%E7%94%A8-https-%E4%BB%A3%E7%90%86) for more info.

Let me know if this solves the 404 issue as well.

**Comment by milukun** [comment]
According to the instructions inside the documentation, I need to set TRUST_PROXY_HEADER to True
https://docs.logto.io/docs/references/core/configuration/

```
Using a HTTPS proxy
Another common practice is to have an HTTPS proxy in front of Node (E.g. Nginx).

In this case, you're likely want to set TRUST_PROXY_HEADER to true which indicates if proxy header fields should be trusted. Logto will pass the value to [Koa app settings](https://github.com/koajs/koa/blob/master/docs/api/index.md#settings).
```

But I found that the setting TRUST_PROXY_HEADER=1 is already included in the deployment yml file:


```
# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:${TAG-latest}
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@postgres:5432
      - ENDPOINT
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```


So it should be set up?
I don't understand how Node works, and I don't really understand 
"The .env file in the project root, which conforms with dotenv format"
Where is the project root mentioned here?
I'm deploying via docker, and I haven't found where the mount directory is, so I don't know where the project root is either.
Thanks for the reply!
