### ISSUE TITLE
feature request: Hide incrementation/decrementation of number inputs

### ISSUE THREAD

**Issue by Olyno** [logto-io/logto#1612]
### What problem did you meet?

It's not very nice to leave the increment and decrement buttons on the passcode. This is happening only on Firefox.

![image](https://user-images.githubusercontent.com/25107942/179851438-5a6d83ac-9ed4-4494-8338-8945b3e27166.png)

### Describe what you'd like Logto to have

You can hide them with the `` -moz-appearance`` field on Firefox. More about it here: https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp

```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
```
