### ISSUE TITLE
bug: ENDPOINT cannot be configurable

### ISSUE THREAD

**Issue by waltcow** [logto-io/logto#1747]
### Describe the bug

LOGTO_URL cannot be configurable

### Expected behavior

LOGTO_URL can be set via environment variable

### How to reproduce?

here is my docker-compose file as follow
```yml
# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:${TAG-latest}
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@postgres:5432
      - ENDPOINT=https://logto.example.com
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

```

when I open Admin Console via `https://logto.example.com` ,  click create account button, it just redirect to 
`https://127.0.0.1:3001/oidc/auth?client_id=admin-console&redirect_uri=https%3A%2F%2Flogto.example.com%2Fconsole%2Fcallback&code_challenge=sa1zL03R9gYGibaj7Bf2Euwq_3s8T92-MPNyUyyNCvY&code_challenge_method=S256&state=_udq2h4pOI31mkJMpacDXjgZ-YFLiZR-PivdHRCD6ckZ3Cq4XxKnXhiYLvbhMT1lJgqki7WPo5UrloWh_MIDCg&response_type=code&prompt=consent&scope=openid+offline_access+profile&resource=https%3A%2F%2Fapi.logto.io`

LOGTO_URL is hard code to `https://127.0.0.1:3001`, this is not configurable from  environment variable

### Context

OS: 

Environment: 

Logto version: 

Node version:

Postgres version: 

Command of starting Logto:

**Comment by charIeszhao** [comment]
What is your docker compose command? And do you use logto behind a reverse proxy, say nginx?

**Comment by gao-sun** [comment]
how did you come with the conclusion that `LOGTO_URL` is hard-coded? also the context is not clear. will re-open the missing info has been fulfilled.

**Comment by waltcow** [comment]
@charIeszhao @gao-sun 

It is my mistake.  i use logto behind nginx proxy, 

I miss `proxy_set_header Host $host ` in forward rule

```nginx
location / {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_pass http://127.0.0.1:8009;
  proxy_redirect off;
}
```

after add it, problem solved,

btw, maybe the getting start of the docs can provide more details for nginx configuration

**Comment by charIeszhao** [comment]
Cool! Thanks for using Logto. Let us know if you come across other issues

**Comment by gao-sun** [comment]
@waltcow glad it works. actually we have a [quick troubleshooting](https://docs.logto.io/docs/tutorials/get-started/#quick-troubleshooting) section - but deosn't have your case.
feel free to submit a PR for adding the case. thanks!

**Comment by waltcow** [comment]
The miss of `proxy_set_header Host $host` lead to ENDPOINT set to `https://127.0.0.1:3001 ` as default , make it looks like `ENDPOINT ` is hard-coded 😭

**Comment by charIeszhao** [comment]
> btw, maybe the getting start of the docs can provide more details for nginx configuration

We thought about this before. However, we can't assume that users are using Logto with nginx, and to be honest, it's a little bit out of our scope. If user wants to use nginx, we assume they should know at least the basics of it. And adding the proxy headers are one of these things.

**Comment by JZLeung** [comment]
My Nginx has this configuration item `proxy_set_header Host $host` , but the message `redirect_uri did not match any of the client's registered redirect_uris` is still displayed.

I modified docker-compose.yml and ran `docker-compose restart`

**Comment by JZLeung** [comment]
> My Nginx has this configuration item `proxy_set_header Host $host` , but the message `redirect_uri did not match any of the client's registered redirect_uris` is still displayed.
> 
> I modified docker-compose.yml and ran `docker-compose restart`

my `docker-compose.yml`:
```yaml
version: "2.1"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:prerelease
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@postgres:5432
      - ENDPOIN=https://logto.mysite.com
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```

and my nginx's proxy config:
```
# Proxy headers
proxy_set_header Upgrade           $http_upgrade;
proxy_set_header Connection        $connection_upgrade;
proxy_set_header Host              $host;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header Forwarded         $proxy_add_forwarded;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host  $host;
proxy_set_header X-Forwarded-Port  $server_port;

# Proxy timeouts
proxy_connect_timeout              60s;
proxy_send_timeout                 60s;
proxy_read_timeout                 60s;
```
