### ISSUE TITLE
bug: Bad port mapping for local docker compose config

### ISSUE THREAD

**Issue by luislve17** [logto-io/logto#3377]
### Describe the bug

Following the _Get started_ section from the documentation, trying to define a port that is not `5432` for logto makes it fail to boot due connection issue with the DB 

### Expected behavior

To connect to the database using any custom port

### How to reproduce?

1. Try to run this **_working_** ✅  docker compose manifest
```yaml
version: "3.8"
services:
  other-db:
    image: postgres:14-alpine
    restart: on-failure
    hostname: other-db
    volumes:
      - pgdata:/var/lib/postgresql/data/:cached
    environment:
    - POSTGRES_USER=devuser
    - POSTGRES_PASSWORD=devpass
    - POSTGRES_DB=devdb
    - PGTZ=UTC
    ports:
      - "50001:5432" # special attention here
    volumes:
      - pgdata:/var/lib/postgresql/data/:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 2

  logto-db:
    image: postgres:14-alpine
    restart: on-failure
    hostname: user-manager-db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=p0stgr3s
    - POSTGRES_DB=logto
    - PGTZ=UTC
    ports:
      - 5432:5432 # special attention here
    volumes:
      - pgdata2:/var/lib/postgresql/data/:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 2

  logto:
    depends_on:
      logto-db:
        condition: service_healthy
    image: svhd/logto:1.0.0-rc.3
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgresql://postgres:p0stgr3s@logto-db:5432/logto # special attention here

      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT
      - ADMIN_ENDPOINT

volumes:
  pgdata:
  pgdata2:

```

This should work properly and boot logto.

2. Change the DB ports in a way that `logto` service no longer uses `5432`

```yaml
version: "3.8"
services:
  other-db:
    image: postgres:14-alpine
    restart: on-failure
    hostname: other-db
    volumes:
      - pgdata:/var/lib/postgresql/data/:cached
    environment:
    - POSTGRES_USER=devuser
    - POSTGRES_PASSWORD=devpass
    - POSTGRES_DB=devdb
    - PGTZ=UTC
    ports:
      - "5432:5432" # Now the other DB is using port `5432`
    volumes:
      - pgdata:/var/lib/postgresql/data/:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 2

  logto-db:
    image: postgres:14-alpine
    restart: on-failure
    hostname: user-manager-db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=p0stgr3s
    - POSTGRES_DB=logto
    - PGTZ=UTC
    ports:
      - 5433:5432 # Now the logto DB is using a port different from `5432` (`5433` for example)
    volumes:
      - pgdata2:/var/lib/postgresql/data/:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 2

  logto:
    depends_on:
      logto-db:
        condition: service_healthy
    image: svhd/logto:1.0.0-rc.3
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgresql://postgres:p0stgr3s@logto-db:5433/logto # Updated port to `5433`

      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT
      - ADMIN_ENDPOINT

volumes:
  pgdata:
  pgdata2:

```

This will fail on logto, displaying on the image's logs:

```node
> cli
> logto db seed --swe

[error] Error: connect ECONNREFUSED 172.22.0.3:5433
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.22.0.3',
  port: 5433
}
npm notice 
npm notice New minor version of npm available! 9.5.0 -> 9.6.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
npm notice Run `npm install -g npm@9.6.1` to update!
npm notic
```

### Context

OS: Ubuntu 22.04.1 LTS x86_64

Environment: docker compose

Logto version: logto:1.0.0-rc.3

Node version: ???

Postgres version: postgres:14-alpine

Command of starting Logto: `entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]`
