### ISSUE TITLE
feature request: Custom schema

### ISSUE THREAD

**Issue by zuohuadong** [logto-io/logto#3795]
### What problem did you meet?

logto uses public schema by default, which hacks into my existing database. If it is separated, the association relationship cannot be guaranteed.

### Describe what you'd like Logto to have
I have  Public (Schema).

 I want the logoto to be in auth instead of public，That's what I'm using.

![image](https://user-images.githubusercontent.com/11203929/235291957-0da60819-b49d-4210-801c-274d191a5dc7.png)

**Comment by gao-sun** [comment]
this is valid, but we don't have resource for now. it's open for contribution and bounty

**Comment by gao-sun** [comment]
you can actually set `search_path` for a Postgres role (user) to the schema you have Logto tables. see [this answer](https://dba.stackexchange.com/questions/56023/what-is-the-search-path-for-a-given-database-and-user).

**Comment by Destreyf** [comment]
@gao-sun have you gotten this to work, when I try to deploy using docker and a dedicated role with a search_path set, I instead get an error:

```
relation "systems" does not exist
```

And then further down:
```
error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.
```

This is using the following docker compose service definition:

```yaml
 logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:1.6.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://logto:postgrespassword@postgres:5432/postgres
```
