### ISSUE TITLE
bug/request: Allow the use of self-signed certificates for webhooks when running locally in a docker container

### ISSUE THREAD

**Issue by jonsamwell** [logto-io/logto#4613]
### Describe the bug
When Logto is run in a Docker container locally (while developing) it would be awesome to allow the use of self-signed certificates for webhook endpoints. At the moment I get a `Message: Failed to send test payload: RequestError: self-signed certificate` when testing the webhook which is an API on the host machine. I've tried a few things but I cannot get it to work.

### How to reproduce?
When running in Docker you can call the host os using host.docker.internal:[PORT].

I've generated a self-signed certificate with 'host.docker.internal' & 'localhost' as the common name for my local API service and added a few environment variables to the docker version of Logto (- NODE_EXTRA_CA_CERTS=/var/tmp/self_signed_certificate.crt & - NODE_TLS_REJECT_UNAUTHORIZED=0). However, I am still getting the error when trying to test the webhook via the Logto admin UI. It would be awesome if the webhook could call out to an API using a self-signed certificate during development.

Docker compose file:
```
  db_auth:
    container_name: postgres_auth
    image: postgres:16.0
    restart: always
    ports:
      - 5105:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logto
    volumes:
      - ./docker_tmp/db_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d logto -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
        
  logto:
    container_name: logto_auth
    image: svhd/logto:1.9.1
    depends_on:
      db_auth:
        condition: service_healthy
    restart: always
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - ./MyApi/cert.crt:/var/tmp/self_signed_certificate.crt
    environment:
      - TRUST_PROXY_HEADER=1
      - NODE_EXTRA_CA_CERTS=/var/tmp/self_signed_certificate.crt
      - NODE_TLS_REJECT_UNAUTHORIZED=0 
      - DB_URL=postgres://admin:admin@db_auth:5432/logto
      
# Webhook URL will be: https://host.docker.internal:7196/logto-webhook
```

### Context
- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.9.1
  - [x] Container (Docker image)
  - [ ] Raw Node.js

<img width="1216" alt="image" src="https://github.com/logto-io/logto/assets/3694497/6c63da56-db0e-46fb-9190-4d309ded55ac">
