### ISSUE TITLE
bug: logto in docker compose not working

### ISSUE THREAD

**Issue by mrefaie** [logto-io/logto#5472]
### Describe the bug

I have installed logto on centos server using docker compose but when trying to access the logto core app or admin app I got the following:

```
[root@static logto]# curl -v 127.0.0.1:3001
* About to connect() to 127.0.0.1 port 3001 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:3001
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by xiaoyijun** [comment]
Hi @mrefaie , It seems that it is not a bug of Logto, please provide more context about:
- How you start your service
- What's the content in your docker compse file

**Comment by mrefaie** [comment]
OS: CentOS Linux release 7.9.2009 (Core)
Docker: Docker version 25.0.3, build 4debf41
Run cmd: docker compose up -d

docker-compose.yml
```
# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@postgres:5432/logto
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT
      - ADMIN_ENDPOINT
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: logto
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres:
```

.env
```
ENDPOINT=https://logto.mydomain.com
ADMIN_ENDPOINT=https://logto-admin.mydomain.com
```

Logs
```
postgres-1  |
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  |
postgres-1  | 2024-03-05 12:08:28.705 UTC [1] LOG:  starting PostgreSQL 14.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres-1  | 2024-03-05 12:08:28.705 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2024-03-05 12:08:28.705 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2024-03-05 12:08:28.711 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-03-05 12:08:28.719 UTC [14] LOG:  database system was shut down at 2024-03-05 12:07:08 UTC
postgres-1  | 2024-03-05 12:08:28.725 UTC [1] LOG:  database system is ready to accept connections
app-1       |
app-1       | > cli
app-1       | > logto db seed --swe
app-1       |
app-1       | info Seeding skipped
app-1       | npm notice
app-1       | npm notice New minor version of npm available! 10.2.4 -> 10.5.0
app-1       | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
app-1       | npm notice Run `npm install -g npm@10.5.0` to update!
app-1       | npm notice
app-1       |
app-1       | > start
app-1       | > cd packages/core && NODE_ENV=production node .
app-1       |
app-1       | (node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
app-1       | (Use `node --trace-warnings ...` to show where the warning was created)
app-1       | warn [CACHE] No Redis client initialized, skipping
app-1       | info Core app is running at http://localhost:3001/
app-1       | info Core app is running at https://logto.mydomain.com/
app-1       | info Admin app is running at http://localhost:3002/
app-1       | info Admin app is running at https://logto-admin.mydomain.com/
```

curl -v localhost:3001
```
* About to connect() to localhost port 3001 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 3001 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3001
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

curl -v localhost:3002
```
* About to connect() to localhost port 3002 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 3002 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3002
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

The server is running behind nginx reverse proxy.

Nginx Config for admin and the same for the other domain:
```
server {
	listen xx.xx.xx.xx:443 ssl http2;
	server_name logto-admin.mydomain.com;
	access_log /usr/local/apache/domlogs/logto-admin.mydomain.com.bytes bytes;
	access_log /usr/local/apache/domlogs/logto-admin.mydomain.com.log combined;
	error_log /usr/local/apache/domlogs/logto-admin.mydomain.com.error.log error;

	ssl_certificate /etc/pki/tls/certs/logto-admin.mydomain.com.bundle;
	ssl_certificate_key /etc/pki/tls/private/logto-admin.mydomain.com.key;
	ssl_protocols TLSv1.2;
	ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA!RC4:EECDH:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;
	ssl_prefer_server_ciphers on;

	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 60m;

	location / {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $http_host;
		proxy_set_header X-NginX-Proxy true;
		include proxy.inc;

		proxy_pass http://127.0.0.1:3002;

		# Socket.IO Support
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}

	add_header X-Cache "HIT from Backend";
	add_header Strict-Transport-Security "max-age=31536000";
	add_header X-Content-Type-Options nosniff;

	location ~ /\.ht {
		deny all;
	}
	location ~ /\.svn/ {
		deny all;
	}
	location ~ /\.git/ {
		deny all;
	}
	location ~ /\.hg/ {
		deny all;
	}
	location ~ /\.bzr/ {
		deny all;
	}

	disable_symlinks if_not_owner from=/home/xxx/public_html;

	location /.well-known/acme-challenge {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}

	location /.well-known/pki-validation {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}
}

server {
	listen xx.xx.xx.xx:80;	
	server_name logto-admin.mydomain.com;
	return 301 https://$server_name$request_uri;
}
```

Server domain is managed by cloudflare with full ssl enabled.
