### ISSUE TITLE
bug: Deployment with nginx reverse proxy

### ISSUE THREAD

**Issue by msfurnadzhiev** [logto-io/logto#5569]
### Describe the bug

When I try to visit `https://my-domain.app:4002`  I get redirected to `https://my-domain.app:4001/unknown-session`.

I have access to `https://my-domain.app:4001/oidc/.well-known/openid-configuration`.

![image](https://github.com/logto-io/logto/assets/37443282/0af7c918-049b-470a-a03b-b049aeb90779)

### Context
* docker-compose.yml

```
version: "3.9"

services:
  app:
    container_name: logto_app
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - ./.env:/etc/logto/.env

  postgres:
    container_name: logto_postgres
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
```

* .env
```
PORT=3001
ADMIN_PORT=3002
TRUST_PROXY_HEADER=1
DB_URL=postgres://postgres:p0stgr3s@postgres:5432/logto
ENDPOINT=https://my-domain.app:4001
ADMIN_ENDPOINT=https://my-domain.app:4002
```
* the nginx config file
```
server {
   listen 4001 ssl;
   server_name my-domain.app;

   ssl_certificate /etc/.../my-domain..app_chained.crt;
   ssl_certificate_key /etc/.../my-domain.app_key.txt;
   ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers         HIGH:!aNULL:!MD5;
   ssl_prefer_server_ciphers on;

   location / {
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto https;

       proxy_pass http://localhost:3001;
   }
   autoindex on;
}

server {
   listen 4002 ssl;
   server_name my-domain.app;

   ssl_certificate /etc/.../my-domain.app_chained.crt;
   ssl_certificate_key /etc/.../my-domain.app_key.txt;
   ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers         HIGH:!aNULL:!MD5;
   ssl_prefer_server_ciphers on;

   location / {
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto https;

       proxy_pass http://localhost:3002;
   }
   autoindex on;
}

```
