### ISSUE TITLE
bug: User "logto_tenant_logto" has no password assigned.'

### ISSUE THREAD

**Issue by sa-mustafa** [logto-io/logto#6430]
### Describe the bug
I encounter the 'Failed to get encrypted password: User "logto_tenant_logto" has no password assigned.' error during seeding process of logto against Koyeb postgres v14 database.

### Expected behavior
This bug is not seen when running logto with local instance of postgresql running in docker.

### How to reproduce?
Put the following text in docker-compose.yaml and run 'docker compose up':
```
version: "3.9"
services:
  app:
    image: svhd/logto:latest
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://logto-adm:Cd05IwRtDxSX@ep-frosty-wave-a24wezje.eu-central-1.pg.koyeb.app/logto?sslmode=require
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT
      - ADMIN_ENDPOINT
```

### Context
I created a postgresql v14 DB instance on koyeb cloud service.

- [ ] Logto Cloud
- [* ] Self-hosted, Logto version 1.19
- [* ] Container (Docker image)
- [ ] Raw Node.js

### Error stack
logto-app-1  |
logto-app-1  | > cli
logto-app-1  | > logto db seed --swe
logto-app-1  |
logto-app-1  | - Create tables
logto-app-1  | info ✔ Create tables
logto-app-1  | info ✔ [default] Generated config oidc.privateKeys
logto-app-1  | info ✔ [default] Generated config oidc.cookieKeys
logto-app-1  | info ✔ [default] Seed OIDC config
logto-app-1  | info ✔ [admin] Generated config oidc.privateKeys
logto-app-1  | info ✔ [admin] Generated config oidc.cookieKeys
logto-app-1  | info ✔ [admin] Seed OIDC config
logto-app-1  | info ✔ Cloud Service Application successfully created for: default
logto-app-1  | info ✔ Created machine-to-machine applications for Management API proxy
logto-app-1  | info ✔ Initialized tenant organization template
logto-app-1  | info ✔ Assigned the proxy roles to the applications
logto-app-1  | info ✔ Created tenant organizations
logto-app-1  | info ✔ Seed data
logto-app-1  | error error: Failed to get encrypted password: User "logto_tenant_logto" has no password assigned.
logto-app-1  |     at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
logto-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
logto-app-1  |     at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:21:13)
logto-app-1  |     at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:74:16)
logto-app-1  |     at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection.js:108:18)
logto-app-1  |     at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/bindPool.js:108:20)
logto-app-1  |     at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
logto-app-1  |     at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
logto-app-1  |   length: 168,
logto-app-1  |   severity: 'ERROR',
logto-app-1  |   code: 'XX000',
logto-app-1  |   detail: undefined,
logto-app-1  |   hint: undefined,
logto-app-1  |   position: undefined,
logto-app-1  |   internalPosition: undefined,
logto-app-1  |   internalQuery: undefined,
logto-app-1  |   where: undefined,
logto-app-1  |   schema: undefined,
logto-app-1  |   table: undefined,
logto-app-1  |   column: undefined,
logto-app-1  |   dataType: undefined,
logto-app-1  |   constraint: undefined,
logto-app-1  |   file: 'control_plane_connector.c',
logto-app-1  |   line: '181',
logto-app-1  |   routine: 'ConstructDeltaMessage'
logto-app-1  | }
logto-app-1  | error Error ocurred during seeding your database.
logto-app-1  |
logto-app-1  |   Nothing has changed since the seeding process was in a transaction.
