### ISSUE TITLE
bug: Use docker-compose to build and access the public network ip to localhost

### ISSUE THREAD

**Issue by moseszane168** [logto-io/logto#6705]
### Describe the bug
 I deployed logto through docker-compose on the cloud server. After deployment, I accessed logto through the public IP and redirected directly to 'http://localhost:3010/unknown-session'. 

### Expected behavior
Normally redirect to ‘http://publicnetworkIP:3011/sign-in’. 

### How to reproduce?
docker and postgreSQL.
docker-compose.yml:
```yaml
version: "3.8"
services:
  logto:
    restart: always
    depends_on:
      logtoPostgres:
        condition: service_healthy
    image: svhd/logto:1.18.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3010:3010
      - 3011:3011
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@logtoPostgres:5432/logto
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - PORT=3010
      - ADMIN_PORT=3011
      - ENDPOINT
      - ADMIN_ENDPOINT
  logtoPostgres:
    restart: always
    image: postgres:14-alpine
    user: root
    volumes:
      - "./.volumes/logto_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
    driver: local
```

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
Docker container：
![image](https://github.com/user-attachments/assets/3ad5fbd8-462f-4356-9978-580af36db28c)

Browser Input：
![image](https://github.com/user-attachments/assets/9da32c35-6d75-47d8-b730-452ba44db238)

Redirect directly to this page：
![image](https://github.com/user-attachments/assets/f0ef17ca-fec2-4542-ac69-bbee907c3a93)
