### ISSUE TITLE
bug: Internal server error when visit dashboard

### ISSUE THREAD

**Issue by ukhack** [logto-io/logto#6812]
```
  logto:
    image: svhd/logto:1.19.0
    container_name: lobe-logto
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
      - 'ENDPOINT=https://lobo-auth-api.xx.top:88'
      - 'ADMIN_ENDPOINT=https://lobo-auth-ui.xx.top:88'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']
```
when i visit dashboard with domain， i got so many Internal server error

![image](https://github.com/user-attachments/assets/c6f6db7e-2344-4489-bc1a-5e4357aac736)

![image](https://github.com/user-attachments/assets/46bc1180-110f-4953-b0c2-8ac7ddc9a338)

![image](https://github.com/user-attachments/assets/3d526eba-231c-415c-95a5-a285bfa219ac)
