### ISSUE TITLE
bug: Signing keys rotation to RSA

### ISSUE THREAD

**Issue by aploskiy** [logto-io/logto#6993]
### Describe the bug
Hi, we recently deployed the latest version of Logto (v1.23.0) to Kubernetes and encountered a bug where we are unable to change the signing key algorithm. We updated it in the Admin Panel (see Screenshot 1), but we are still receiving JWTs with "alg": "ES384". The token and Screenshot 2 of the token call are attached.

We tried troubleshooting by using incognito mode, logging out, and even testing on different PCs, but the issue persists.

This issue does not occur in the cloud version, where the algorithm successfully switches to RSA. Unfortunately, we are unable to switch our application to ES384, making this a blocking issue.

```json
{
  "alg": "ES384",
  "typ": "JWT",
  "kid": "VmSg755A01sqks_hSl0LGj0dQ3a3di99CyRWEybsrBw"
}
```

### Expected behavior
We expect to receive JWT tokens signed with the RSA algorithm.

### How to reproduce?
	1.	Rotate the private key to RSA.
	2.	Call the authentication endpoint /oidc/auth.
	3.	Exchange the code for a token using the /oidc/token endpoint.

### Context

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dx-logto-config-map
data:
  ENDPOINT: "{{ .Values.env.urls.logto }}"
  ADMIN_ENDPOINT: "{{ .Values.env.urls.logto_admin }}"
  DB_URL: "{{ .Values.env.database.url }}"
  TRUST_PROXY_HEADER: "1"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dx-logto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dx-logto
  template:
    metadata:
      labels:
        app: dx-logto
    spec:
      imagePullSecrets:
        - name: "{{ .Values.docker.imagePullSecret }}"
      initContainers:
        - name: dx-logto-connector-init
          image: "{{ .Values.docker.image }}"
          imagePullPolicy: Always
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run cli connector link'
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/packages/core/connectors
      containers:
        - name: dx-logto
          image: "{{ .Values.docker.image }}"
          imagePullPolicy: Always
          {{/*
            For multiple instances need to add DB JOB and remove comman and args
            https://docs.logto.io/logto-oss/deployment-and-configuration
           */}}
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run cli db seed -- --swe && npm start'
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/packages/core/connectors
          ports:
            - name: logto
              containerPort: 3001
            - name: logto-admin
              containerPort: 3002
          envFrom:
            - configMapRef:
                name: dx-logto-config-map
      volumes:
        - name: connectors
          emptyDir: { }
---

apiVersion: v1
kind: Service
metadata:
  name: dx-logto
spec:
  selector:
    app: dx-logto
  ports:
    - name: logto
      port: 3001
      targetPort: logto
    - name: logto-admin
      port: 3002
      targetPort: logto-admin
```

### Screenshots
Screenshot 1.

<img width="1323" alt="Image" src="https://github.com/user-attachments/assets/0ad3cbdd-32f2-42cb-a500-787288bf3bb6" />
