### ISSUE TITLE
bug: Unauthorized. Please check credentials and its scope.

### ISSUE THREAD

**Issue by rftglyv** [logto-io/logto#7412]
### Describe the bug

When I go to dashboard inside the Admin Console or try to touch anything it gives 401 "Unauthorized. Please check credentials and its scope."

### Expected behavior

Must open the dashboard inside the Admin Console.

### How to reproduce?

I've built it with Dokploy template (docker compose).

```
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:1.28.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001
      - 3002

    environment:
      TRUST_PROXY_HEADER: 1
      DB_URL: postgres://logto:${LOGTO_POSTGRES_PASSWORD}@postgres:5432/logto
      ENDPOINT: ${LOGTO_ENDPOINT}
      ADMIN_ENDPOINT: ${LOGTO_ADMIN_ENDPOINT}
    volumes:
      - logto-connectors:/etc/logto/packages/core/connectors
  postgres:
    image: postgres:17-alpine
    user: postgres

    environment:
      POSTGRES_USER: logto
      POSTGRES_PASSWORD: ${LOGTO_POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dokploy-network:
    external: true

volumes:
  logto-connectors:
  postgres-data:
```

### Environment

Self-hosted (Docker image)

### Screenshots

![Image](https://github.com/user-attachments/assets/93a1beb1-bc63-46e1-ab1e-2cde5dcc298b) 

![Image](https://github.com/user-attachments/assets/13b5fe59-9b1f-45fd-aea2-72843316b367) 

![Image](https://github.com/user-attachments/assets/ec0a68e5-c981-4c7f-92d6-e436e31636ff) 

![Image](https://github.com/user-attachments/assets/1fcba0e9-9b47-4a57-9c13-1e01d1a3908d)

![Image](https://github.com/user-attachments/assets/458f2ec9-3fa1-4f75-9b7f-9ba201ae2368)
